const constants = {
  LOGO_TITLE: "SocialMedia",
  DARK: "dark",
  LIGHT: "light",
  DESKTOP_MEDIA_QUERY: "(min-width:1100px)",
  MOBILE_MEDIA_QUERY: "(max-width:600px)",
  LOGIN_INTRODUCE: "Bienvenido a $LOGO_TITLE!",
  DEFAULT_FIELD_REQUIRED_ERROR: "campo requerido",
  DEFAULT_FIELD_EMAIL_ERROR: "email inválido",
  LOGIN_LINK: "Aún no tienes una cuenta? Registrate aquí",
  REGISTER_LINK: "Si ya tienes cuenta, Inicia aquí",
  LOGIN_BUTTON: "Iniciar Sesión",
  REGISTER_BUTTON: "Registrarse",
  GENERAL_ERROR: "Ha ocurrido un error, vuelva a intentarlo más tarde",
  Friends: "Amigos",
  VIEWED_LABEL: "Who's viewed your profile",
  IMPRESSIONS_LABEL: "Impressions of your post",
  TWITTER: "Twitter",
  SOCIAL_NETWORK: "Social Network",
  SOCIAL_PROFILE: "Social Profile",
  LINKEDIN: "LinkedIn",
  NETWORK_PLATFORM: "Network Platform",
  PLACEHOLDER_INPUT_POST: "What's on your mind...",
  IMAGE: "Imagen",
  CLIP: "Clip",
  AUDIO: "Audio",
  ATTACHMENT: "Attachment",
  POST: "POST",
  SPONSORED: "Sponsored",
  CREATE_AD: "Create Ad",
  MIKA_COSMETICS: "MikaCosmetics",
  MIKA_COSMETICS_URL: "mikacosmetics.com",
  DESCRIPTIONS_AD:
    "Your pathway to stunning and immaculate beauty and made sure your skin is exfoliating skin and shining like light.",
  FRIEND_LIST_TITLE: "Lista de amigos",
};

export default constants;
